### PR TITLE
Update Routing and Reconfigure Styling

### PR DESCRIPTION
**Pull request by mndzamel**
The [first commit](https://github.com/Comp-490-SeniorProject/site/commit/e1f071ca6720f83f06d5bd0d2ad9b3c2a4c730de) contains most of the routing and styling fixes. Updated the routing and paths in `app-routing.module.ts` so that the majority of the site pages link together. Different layout components are used for subsets of pages.

The login functionality is currently still being worked on so there is a test admin component in place of the device overview page. To go from the main pages to the pages related to the device, add `/my-devices` to the url and use the links in the header and sidebar to navigate the site.

The styles that were initially applied globally in `styles.scss` were either commented out or moved to the appropriate component folder and modified in the .scss and .html files, with some additional Bootstrap if necessary. Google Fonts imports were not functioning so they are commented out for now; there may be extra steps needed to make them work with webpack. Bootstrap was installed using the `npm install bootstrap` command.

The [second commit](https://github.com/Comp-490-SeniorProject/site/commit/e69e1d61cdc8c16d2cb777fbac24b7a7cb2c20aa) includes modifications of layouts, headers, sidebars, and the footer to make them more responsive and align together correctly. Basic Bootstrap card components were added to pages related to the device for consistency and to match the initial prototype design for presentation purposes.

### CODE REVIEW

**Review by MarkKoz — CHANGES_REQUESTED** [review]
I'm not sure if I'll be able to review your actual changes, but I can comment on one obvious issue.

You accidentally checked in the node modules directory, which contains the third party dependencies. This probably happened when you installed bootstrap. It's my fault for not being clearer about this — the way Angular is set up within Django may be a bit unintuitive. To install node modules through npm, you should `cd` into the `web/frontend/angular` directory. This is just like you did when you first installed dependencies according to the instructions in CONTRIBUTING.md. It's done this way so that `npm` will detect the extant `package.json` in that directory and add the new dependency to it. Note that `node_modules` is already ignored by git if it's within that directory.

**Comment by mndzamel** [comment]
> I'm not sure if I'll be able to review your actual changes, but I can comment on one obvious issue.
> 
> You accidentally checked in the node modules directory, which contains the third party dependencies. This probably happened when you installed bootstrap. It's my fault for not being clearer about this — the way Angular is set up within Django may be a bit unintuitive. To install node modules through npm, you should `cd` into the `web/frontend/angular` directory. This is just like you did when you first installed dependencies according to the instructions in CONTRIBUTING.md. It's done this way so that `npm` will detect the extant `package.json` in that directory and add the new dependency to it. Note that `node_modules` is already ignored by git if it's within that directory.

Okay, thanks for pointing that out. I didn't realize I was in the wrong directory when installing Bootstrap. Is there a specific way to remove the node modules directory or uninstall Bootstrap so I can install it in the correct directory?

**Comment by MarkKoz** [comment]
> Is there a specific way to remove the node modules directory or uninstall Bootstrap

Just delete the node_modules directory, the package.json file, and the lock file generated in the root.

**Comment by mndzamel** [comment]
> Just delete the node_modules directory, the package.json file, and the lock file generated in the root.

I deleted these files and ran `npm install bootstrap` in the `web/frontend/angular` directory but those same files are generated in the same places I deleted them from. How should this be fixed?

**Comment by MarkKoz** [comment]
Looks like you fixed that now.

**Pull request merged**
